stages:
  - build
  - test
  - deploy

backend_build:
  stage: build
  image: mvn:latest
  before_script:
    - cd backend/
  script:
    - echo "Backend Build Started"
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
    - mvn clean install
    - echo "Backend Build Completed"

backend_test:
  stage: test
  image: mvn:latest
  before_script:
    - cd backend/
  script:
    - echo "Backend tests Started"
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
    - mvn test
    - echo "Backend Tests Completed"
