stages:
  - build
  - test
  - deploy

backend_build:
  stage: build
  image: maven:3.9.7-sapmachine-17
  before_script:
    - cd backend/
  script:
    - echo "Backend Build Started"
    - mvn clean install
    - echo "Backend Build Completed"
  tags:
    - dalfcs_gitlab_docker_ci

frontend_build:
  stage: build
  image: node:latest
  before_script:
    - cd frontend/
  script:
    - echo "Frontend Build Started"
    - npm install
    - npm run build
    - echo "Frontend Build Completed"
  tags:
    - dalfcs_gitlab_docker_ci

backend_test:
  stage: test
  image: maven:3.9.7-sapmachine-17
  before_script:
    - cd backend/
  script:
    - echo "Backend tests Started"
    - mvn test
    - echo "Backend Tests Completed"
  tags:
    - dalfcs_gitlab_docker_ci
