stages:
  - build
  - test
  - deploy

backend_build:
  stage: build
  image: mvn:3.9.7-sapmachine-17
  before_script:
    - cd backend/
  script:
    - echo "Backend Build Started"
    - mvn clean install
    - echo "Backend Build Completed"

backend_test:
  stage: test
  image: mvn:3.9.7-sapmachine-17
  before_script:
    - cd backend/
  script:
    - echo "Backend tests Started"
    - mvn test
    - echo "Backend Tests Completed"
