stages:
  - build
  - test
  - deploy

variables:
  DOCKER_USERNAME: ""
  DOCKER_PASSWORD:  ""

backend_build:
  stage: build
  image: mvn:3.9.7-sapmachine-17
  before_script:
    - cd backend/
  script:
    - echo "Backend Build Started"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
    - mvn clean install
    - echo "Backend Build Completed"
  after_script:
    - docker logout
  tags:
    - dalfcs_docker_autoscale

backend_test:
  stage: test
  image: mvn:3.9.7-sapmachine-17
  before_script:
    - cd backend/
  script:
    - echo "Backend tests Started"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
    - mvn test
    - echo "Backend Tests Completed"
  after_script:
    - docker logout
  tags:
    - dalfcs_docker_autoscale
